doctype html;
html {
    head {
        title {
            'Shoko'
        }
        
        link[rel="stylesheet", href="style.css"];
    }
    
    body[style="margin: 0;"] {
        .nav-container {
            nav.nav {
                ul.nav-list {
                    for(link in @links@) {
                        li { 
                            a[href="https://github.com/nirkog/shoko"] {
                                @link@ 
                            }
                        }
                    }
                }
            }
        }
    }
}